namespace GBEmu {
    public enum Instruction {
        //8-bit load instructions
        LD_r_r,
        LD_r_n,
        LD_r_HL,
        LD_HL_r,
        LD_HL_n,
        LD_A_BC,
        LD_A_DE,
        LD_BC_a,
        LD_DE_a,
        LD_A_nn,
        LD_nn_A,
        LDH_A_C,
        LDH_C_A,
        LDH_A_n,
        LDH_n_A,
        LD_A_HLSub,
        LD_HLSub_A,
        LD_A_HLAdd,
        LD_HLAdd_A,
        //16-bit load instructions
        LD_rr_nn,
        LD_nn_SP,
        LD_SP_HL,
        PUSH_rr,
        POP_rr,
        //Arithmetic instructions
        ADC_A_n,
        ADD_A_n,
        ADD_HL_n,
        ADD_SP_n,
        SUB_n,
        SBC_A_n,
        DEC_n,
        DEC_nn,
        INC_n,
        INC_nn,        
        //Rotate, shift and bit operation instructions
        SET_b_r,
        RL_n,
        RLC_n,
        RR_n,
        RRC_n,
        SRA_n,
        SRL_n,
        SWAP_n,
        XOR_n,

        //Control flow instructions
        JP_nn,
        JP_HL,
        JP_cc_nn,
        JR_e,
        JR_cc_e,
        CALL_nn,
        CALL_cc_nn,
        RET,
        RET_cc,
        RETI,
        RST_n,
        //Miscellaneous instructions
        HALT,
        STOP,
        DI,
        EI,
        CCF,
        SCF,
        NOP,
        DAA,
        CPL,   
    }
}
